ALTER TABLE users
    ADD COLUMN IF NOT EXISTS cpf_cnpj VARCHAR(14),
    ADD COLUMN IF NOT EXISTS birth_date DATE,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(32),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS instagram VARCHAR(100),
    ADD COLUMN IF NOT EXISTS linkedin VARCHAR(255);